version: '3'

services:
  minetrack:
    build: .
    container_name: minetrack
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    volumes:
      - ${MINETRACK_DATA}/database.sql:/usr/src/minetrack/database.sql
    labels:
      - traefik.enable=true
      - traefik.http.routers.minetrack.rule=Host(`track.antiskid.club`)
      - traefik.http.routers.minetrack.entrypoints=https
      - traefik.http.services.minetrack.loadbalancer.server.port=8080
