version: '3'

services:
  minetrack:
    build: .
    container_name: minetrack
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    volumes:
      - ${MINETRACK_DATA}/database.sql:/usr/src/minetrack/database.sql
    labels:
      - traefik.enable=true
      - traefik.http.routers.guides.rule=Host(`track.antiskid.club`)
      - traefik.http.routers.guides.entrypoints=https
      - traefik.http.services.guides.loadbalancer.server.port=8080
